version: 1

bindings:
  - enter:become(puts :{1})
  - alt-o:become(puts code:{1})
  - alt-1:become(puts ctxsel:{})

alias:
  chrome: C:\Program Files\Google\Chrome\Application\chrome.exe

list:
  - |-
    ncpa.cpl
    cmd
    /c ncpa.cpl
  - |-
    power shell
    powershell
  - |-
    google.com
    chrome
    https://www.google.com
  - |-
    desktop
    (ff)
    C:\Users\bamch\Desktop
  - |-
    chatgpt
    chrome
    https://chatgpt.com/
  - |-
    puts
  - |-
    fortnite
    explorer
    "C:\Users\bamch\Desktop\フォートナイト.url"
